// Package words produces target strings for typing tests.
// It embeds a common-English word list and a curated quote pack so that the
// binary has no runtime filesystem or network dependencies.
package words

import (
	_ "embed"
	"math/rand/v2"
	"strconv"
	"strings"
	"time"
	"unicode"
)

//go:embed data/english-1000.txt
var wordListRaw string

// wordList is parsed once at init time from the embedded text file.
// Each element is a lowercase ASCII word; blank lines are skipped.
var wordList []string

func init() {
	for _, line := range strings.Split(wordListRaw, "\n") {
		w := strings.TrimSpace(line)
		if w != "" {
			wordList = append(wordList, w)
		}
	}
}

// timeBufferWords is the number of words generated by TimeBuffer.
// At 120 WPM sustained for 120 seconds a typist produces ~240 words;
// 600 provides a comfortable 2.5× headroom with no mid-test regeneration.
const timeBufferWords = 600

// Generator is a seedable random word/quote source. Construct one with
// NewGenerator; the zero value is not valid.
type Generator struct {
	rng *rand.Rand
}

// NewGenerator returns a Generator seeded with seed.
// If seed is 0 a unique time-based seed is chosen so each run differs.
func NewGenerator(seed int64) *Generator {
	var src rand.Source
	if seed == 0 {
		src = rand.NewPCG(uint64(time.Now().UnixNano()), 0)
	} else {
		src = rand.NewPCG(uint64(seed), 0)
	}
	return &Generator{rng: rand.New(src)}
}

// Words returns n space-separated words drawn at random from the embedded
// word list. When n <= 0 an empty string is returned.
func (g *Generator) Words(n int) string {
	if n <= 0 || len(wordList) == 0 {
		return ""
	}
	tokens := make([]string, n)
	for i := range tokens {
		tokens[i] = wordList[g.rng.IntN(len(wordList))]
	}
	return strings.Join(tokens, " ")
}

// TimeBuffer returns a large pool of space-separated words sized to outlast a
// 120-second test at high typing speed (timeBufferWords words). The caller
// (Phase 4 typing screen) may call TimeBuffer again to extend the pool if the
// user somehow exhausts it.
func (g *Generator) TimeBuffer() string {
	return g.Words(timeBufferWords)
}

// punctuationMarks are trailing marks applied to a token; earlier entries are
// weighted more heavily by repetition (commas more common than semicolons).
var punctuationMarks = []byte{',', ',', ',', '.', '.', ';'}

// ApplyOptions returns text with punctuation and/or number substitutions
// applied, using the Generator's own seeded rng so output stays deterministic
// per seed. Token count is always preserved: punctuation only appends marks
// or capitalizes existing tokens, and numbers only replaces a token in place
// — neither adds nor removes word slots. A no-op (both flags false) returns
// text unchanged.
func (g *Generator) ApplyOptions(text string, punctuation, numbers bool) string {
	if !punctuation && !numbers {
		return text
	}
	tokens := strings.Fields(text)
	if len(tokens) == 0 {
		return text
	}
	if numbers {
		g.applyNumbers(tokens)
	}
	if punctuation {
		g.applyPunctuation(tokens)
	}
	return strings.Join(tokens, " ")
}

// applyNumbers substitutes ~10-15% of tokens with a random 1-4 digit string.
func (g *Generator) applyNumbers(tokens []string) {
	for i := range tokens {
		if g.rng.IntN(100) < 12 {
			digits := g.rng.IntN(4) + 1
			max := 1
			for range digits {
				max *= 10
			}
			// IntN(max-1)+1 bounds the result to [1, max-1], i.e. exactly
			// `digits` digits — IntN(max)+1 would include max itself (one
			// digit too many, e.g. 10000 when digits==4).
			tokens[i] = strconv.Itoa(g.rng.IntN(max-1) + 1)
		}
	}
}

// applyPunctuation appends trailing marks to ~15-20% of tokens, wraps ~2-3%
// of tokens in quotes, capitalizes the token following a period or
// semicolon, and always closes the final token with a mark. Applied after
// applyNumbers so a numeric token can also be punctuated.
func (g *Generator) applyPunctuation(tokens []string) {
	capitalizeNext := false
	for i, tok := range tokens {
		if capitalizeNext {
			tokens[i] = capitalizeFirst(tok)
			capitalizeNext = false
		}
		if g.rng.IntN(100) < 3 {
			tokens[i] = `"` + tokens[i] + `"`
		}
		last := i == len(tokens)-1
		roll := g.rng.IntN(100)
		switch {
		case last:
			tokens[i] = tokens[i] + "."
		case roll < 17:
			mark := punctuationMarks[g.rng.IntN(len(punctuationMarks))]
			tokens[i] = tokens[i] + string(mark)
			if mark == '.' || mark == ';' {
				capitalizeNext = true
			}
		}
	}
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
