// Package words produces target strings for typing tests.
// It embeds a common-English word list and a curated quote pack so that the
// binary has no runtime filesystem or network dependencies.
package words

import (
	_ "embed"
	"math/rand/v2"
	"strings"
	"time"
)

//go:embed data/english-1000.txt
var wordListRaw string

// wordList is parsed once at init time from the embedded text file.
// Each element is a lowercase ASCII word; blank lines are skipped.
var wordList []string

func init() {
	for _, line := range strings.Split(wordListRaw, "\n") {
		w := strings.TrimSpace(line)
		if w != "" {
			wordList = append(wordList, w)
		}
	}
}

// timeBufferWords is the number of words generated by TimeBuffer.
// At 120 WPM sustained for 120 seconds a typist produces ~240 words;
// 600 provides a comfortable 2.5× headroom with no mid-test regeneration.
const timeBufferWords = 600

// Generator is a seedable random word/quote source. Construct one with
// NewGenerator; the zero value is not valid.
type Generator struct {
	rng *rand.Rand
}

// NewGenerator returns a Generator seeded with seed.
// If seed is 0 a unique time-based seed is chosen so each run differs.
func NewGenerator(seed int64) *Generator {
	var src rand.Source
	if seed == 0 {
		src = rand.NewPCG(uint64(time.Now().UnixNano()), 0)
	} else {
		src = rand.NewPCG(uint64(seed), 0)
	}
	return &Generator{rng: rand.New(src)}
}

// Words returns n space-separated words drawn at random from the embedded
// word list. When n <= 0 an empty string is returned.
func (g *Generator) Words(n int) string {
	if n <= 0 || len(wordList) == 0 {
		return ""
	}
	tokens := make([]string, n)
	for i := range tokens {
		tokens[i] = wordList[g.rng.IntN(len(wordList))]
	}
	return strings.Join(tokens, " ")
}

// TimeBuffer returns a large pool of space-separated words sized to outlast a
// 120-second test at high typing speed (timeBufferWords words). The caller
// (Phase 4 typing screen) may call TimeBuffer again to extend the pool if the
// user somehow exhausts it.
func (g *Generator) TimeBuffer() string {
	return g.Words(timeBufferWords)
}
